### ISSUE TITLE
!me support

### ISSUE THREAD

**Issue by mattiasr** [mattiasr/phoenix-herald#24]
!me add <name> or <list of names> to add your char(s)
!me, get info from all your chars in short summary

**Comment by teehehe** [comment]
can we get !me to sort based on char with most RP's and possibly a total of all chars added together rps

**Comment by mattiasr** [comment]
I already thought about sort on most rp, will change that to default and only mode.

don't see the reason with all chars rp summed up, more than to tell you that you should have sticked with one char :P

**Comment by teehehe** [comment]
> I already thought about sort on most rp, will change that to default and only mode.
> 
> don't see the reason with all chars rp summed up, more than to tell you that you should have sticked with one char :P

true but some friends have like rr9s on different realms just thought it would be nice lol and some people are altoholics like myself
