### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by teehehe** [mattiasr/phoenix-herald#37]
its not saving saving the database? once I reboot or relaunch it !me comes back with no saved chars

**Comment by mattiasr** [comment]
Do you run it in a docker container? and if so, do you have the db mounted with -v ? on windows that's a little tricky with docker

**Comment by teehehe** [comment]
yes but im not sure if the mounting part is right it goes to the location but is no sqlite file there do you have a discord or something can talk direct?
Teehehe#9239

**Comment by mattiasr** [comment]
join the support channel for the bot 📦 
5hxyfka
